#!/command/with-contenv bash
source /assets/functions/00-container
source /assets/defaults/10-s3ql
PROCESS_NAME=fsck-now

sanity_var S3_HOST "S3 Storage URL"
sanity_var S3_KEY_ID "S3 Key ID"
sanity_var S3_KEY_SECRET "S3 Key Secret"

fsck_cli_args=$@
log_fsck="${LOG_PATH}"/$(date %Y-%m-%d.%H:%M:%S)-fsck_$(echo "\${S3_HOST}" | cut -d / -f 3.log)

if var_true "${ENABLE_CACHE}" ; then
    s3ql_cachedir_arg="--cachedir ${CACHE_PATH}"
    if var_true "${ENABLE_PERSISTENT_CACHE}" ; then
        s3ql_cachedir_arg+=" --keep-cache"
    fi
fi

print_notice "Performing S3QL Filesystem check on '${S3_HOST}'"

fsck.s3ql \
        --log ${log_fsck} \
        --authfile "${CONFIG_PATH}"/"${CONFIG_FILE}" \
        --compression "${COMPRESSION}"
        ${s3ql_cachedir_arg} "${S3_HOST}" ${FSCK_ARGS} ${fsck_cli_args}
