#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="s3ql"
prepare_service defaults single

check_container_initialized
check_service_initialized init

if var_true "${ENABLE_CACHE}" ; then
    s3ql_cachedir_arg="--cachedir ${CACHE_PATH} "
    if [ "${CACHE_SIZE,,}" != "auto" ] ; then
        s3ql_cache_size="--cachesize ${CACHE_SIZE}"
    fi

    if var_true "${ENABLE_PERSISTENT_CACHE}" ; then
        s3ql_cache_peresistent_arg="--keep-cache"
    fi
fi

if [ "${LOG_TYPE,,}" = "file" ] ; then
    exec_arg=silent
    log_s3ql="${LOG_PATH}"/$(date +'%Y%m%d%H%M%S')-mount_$(echo "${S3_HOST}" | cut -d / -f 4).log
else
    log_s3ql="none"
fi

liftoff

print_start "Starting S3QL ${S3QL_VERSION} for host: '${S3_HOST}'"
${exec_arg} exec /usr/bin/mount.s3ql \
                            --authfile "${CONFIG_PATH}"/"${CONFIG_FILE}" \
                            --allow-other \
                            --compress "${COMPRESSION}" \
                            --fg \
                            --log "${log_s3ql}" \
                            ${s3ql_cachedir_arg} ${s3ql_cache_persistent_arg} ${s3ql_cache_size} ${S3QL_ARGS} "${S3_HOST}" \
                            "${DATA_PATH}"